// This file is auto-generated by Convex.
// Run `npx convex dev` to generate the real file.

import { queryGeneric, mutationGeneric } from "convex/server";
import { v } from "convex/values";

// Re-export as query/mutation for backwards compatibility
export const query = queryGeneric;
export const mutation = mutationGeneric;
export { v };
