/**
 * Stub API — generated by `npx convex dev`.
 * This file is replaced with real generated types when Convex is set up.
 *
 * DO NOT edit this file manually.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const api: any = {};
