/**
 * Stub API — generated by `npx convex dev`.
 * This file is a placeholder until `npx convex dev` runs and generates the real types.
 *
 * To regenerate: npx convex dev
 */
export const api = {};
