"use client";

import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import { Zap, Calendar, MessageCircle, CheckCircle2, BarChart3, Users, Wand2, FolderOpen, ShieldCheck, Megaphone, TrendingUp, Globe, Smartphone } from "lucide-react";
import { useCategory } from "@/components/providers/CategoryProvider";
import { ScrollReveal } from "@/components/ScrollReveal";
import type { Category } from "@/components/providers/CategoryProvider";

const FEATURES: Record<Category, { icon: React.ElementType; tag: string; title: string; desc: string }[]> = {
  creator: [
    { icon: Wand2, tag: "AI Content", title: "Reels Generated by AI", desc: "Upload a clip. AI creates 3–5 reel concepts with captions, hooks, on-screen text, and hashtags optimised for your niche." },
    { icon: Calendar, tag: "Scheduling", title: "Smart Scheduling", desc: "Auto-posts at your best-performing times. Visual calendar, queue management — all your content in one place." },
    { icon: MessageCircle, tag: "Community", title: "Unified Inbox", desc: "All comments and DMs in one place. Auto-reply rules for FAQs. Never miss a collab request or brand DM again." },
    { icon: TrendingUp, tag: "Analytics", title: "Track Your Growth", desc: "Follower count, reach, engagement pulled weekly. Know what's working so you can double down on what's winning." },
    { icon: CheckCircle2, tag: "Approvals", title: "Client Approval Portal", desc: "Send a one-click link to brands or clients. They review, approve or request changes. No chasing, no spreadsheets." },
    { icon: BarChart3, tag: "Performance", title: "Content Performance", desc: "See which reels are pulling reach, saves, and shares. AI recommends what to post next based on your top content." },
  ],
  agency: [
    { icon: Users, tag: "Multi-Account", title: "Manage All Clients", desc: "One dashboard for every client account. Switch between models, influencers, and brands in seconds — no logging in and out." },
    { icon: FolderOpen, tag: "Brief Pipeline", title: "Model Brief Platform", desc: "Send filming briefs to models with instructions, props, and outfit notes. Receive completed content straight to Drive." },
    { icon: CheckCircle2, tag: "Approvals", title: "PTP Approval Portal", desc: "Clients review finished reels with one link. Approve, request revision, or reject. Approved content auto-schedules." },
    { icon: ShieldCheck, tag: "Permissions", title: "Role-Based Access", desc: "Give VAs and editors access without giving away the keys. Activity logs track every action across all client accounts." },
    { icon: Megaphone, tag: "Content Pipeline", title: "Full Content Pipeline", desc: "Raw clips → AI enhancement → Airdrop/Drive sync → PTP approval → Scheduled. The whole loop, automated." },
    { icon: BarChart3, tag: "Reporting", title: "Agency Analytics", desc: "White-label performance reports for clients. Per-account breakdowns, weekly summaries, and growth tracking in one view." },
  ],
  business: [
    { icon: Wand2, tag: "AI Content", title: "Posts Written for You", desc: "AI writes your captions, picks your hashtags, and suggests what to say about today's special or product drop — every single day." },
    { icon: Smartphone, tag: "Reels", title: "Short-Form Video", desc: "Turn your products, space, or service into scroll-stopping reels. AI handles the concept, script, and on-screen text." },
    { icon: Calendar, tag: "Scheduling", title: "Auto-Post Daily", desc: "Set it and forget it. Your posts go out automatically at peak times for your audience — no reminding, no logging in." },
    { icon: MessageCircle, tag: "Reputation", title: "Review Highlights", desc: "Pull your best reviews into beautiful posts. Let your customers sell for you with user-generated content and testimonials." },
    { icon: Globe, tag: "Local SEO", title: "Local Discovery", desc: "Hashtags, captions, and content optimised for local discovery. Get found by people searching your area on Instagram." },
    { icon: TrendingUp, tag: "Growth", title: "Track Results", desc: "See follower growth, reach, and engagement without guessing. Weekly reports so you can see what's working in plain English." },
  ],
};

function FeatureCard({ icon: Icon, tag, title, desc, delay }: { icon: React.ElementType; tag: string; title: string; desc: string; delay: number }) {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 24 }}
      animate={isInView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.5, delay, ease: [0.25, 0.1, 0.25, 1] }}
      whileHover={{ y: -3, transition: { duration: 0.2 } }}
      className="group relative p-8 rounded-2xl border transition-all cursor-default"
      style={{ borderColor: "rgba(255,255,255,0.06)", backgroundColor: "rgba(18,18,18,0.3)" }}
      onMouseEnter={e => { e.currentTarget.style.borderColor = "rgba(255,0,105,0.25)"; e.currentTarget.style.backgroundColor = "rgba(18,18,18,0.6)"; }}
      onMouseLeave={e => { e.currentTarget.style.borderColor = "rgba(255,255,255,0.06)"; e.currentTarget.style.backgroundColor = "rgba(18,18,18,0.3)"; }}
    >
      <span className="inline-block px-3 py-1 rounded-full text-xs font-bold text-white mb-5" style={{ background: "linear-gradient(135deg, rgba(255,0,105,0.2), rgba(131,58,180,0.2))" }}>{tag}</span>
      <div className="w-9 h-9 rounded-lg mb-4 flex items-center justify-center" style={{ backgroundColor: "rgba(255,0,105,0.08)" }}>
        <Icon size={17} style={{ color: "#ff0069" }} />
      </div>
      <h3 className="text-lg font-bold text-white mb-3">{title}</h3>
      <p className="text-sm leading-relaxed" style={{ color: "#9d7ac8" }}>{desc}</p>
    </motion.div>
  );
}

const HEADLINES: Record<Category, string> = {
  creator: "Everything a creator needs\nto post viral content daily.",
  agency: "Every tool an agency needs\nto scale without hiring.",
  business: "Everything a local business needs\nto own their Instagram.",
};

export function FeatureGrid() {
  const { category } = useCategory();
  const features = FEATURES[category];
  const headline = HEADLINES[category];

  return (
    <section id="features" className="py-24 px-6">
      <div className="mx-auto max-w-6xl">
        <ScrollReveal>
          <div className="text-center mb-16">
            <p className="text-sm font-semibold uppercase tracking-[0.2em] mb-4" style={{ color: "#ff0069" }}>Platform Features</p>
            <h2 className="text-4xl md:text-5xl font-bold tracking-tight text-white whitespace-pre-line">
              {headline}
            </h2>
          </div>
        </ScrollReveal>
        <motion.div
          key={category}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.3 }}
          className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5"
        >
          {features.map((f, i) => <FeatureCard key={f.title} {...f} delay={i * 0.07} />)}
        </motion.div>
      </div>
    </section>
  );
}
