// Auto-generated by Convex (run `npx convex dev` to regenerate)
// Stub until Convex generates the real types
import { makeFunctionReference } from "convex/server";

export const api = {
  ideas: {
    generate: makeFunctionReference("ideas/generate"),
    list: makeFunctionReference("ideas/list"),
    create: makeFunctionReference("ideas/create"),
    updateStatus: makeFunctionReference("ideas/updateStatus"),
  },
  models: {
    list: makeFunctionReference("models/list"),
    ideas: makeFunctionReference("models/ideas/list"),
  },
  content: {
    enhance: makeFunctionReference("content/enhance"),
    upload: makeFunctionReference("content/upload"),
  },
  pipeline: {
    list: makeFunctionReference("pipeline/list"),
    sendToPipeline: makeFunctionReference("pipeline/sendToPipeline"),
    updateStatus: makeFunctionReference("pipeline/updateStatus"),
  },
};